config/routes.rb
Twitter::Application.routes.draw do

  root :to => "tweets#index"
  post '/tweets/create/' => "tweets#create"
  get '/tweets/new' => "tweets#new"
  get '/tweets' => "tweets#index"
  get '/login' => "sessions#new"
  get '/auth' => "sessions#create"
  get '/logout' => "sessions#destroy"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def oauth_consumer
    raise RuntimeError, "You must set TWITTER_KEY and TWITTER_SECRET in your server environment." unless ENV['TWITTER_KEY'] and ENV['TWITTER_SECRET']
    @consumer ||= OAuth::Consumer.new(
      ENV['TWITTER_KEY'],
      ENV['TWITTER_SECRET'],
      :site => "https://api.twitter.com"
      )
  end

  def request_token
    if not session[:request_token]
    # this 'host_and_port' logic allows our app to work both locally and on Heroku
    host_and_port = request.host
    host_and_port << ":3000" if request.host == "localhost"

    # the `oauth_consumer` method is defined above
    session[:request_token] = oauth_consumer.get_request_token(
      :oauth_callback => "http://#{host_and_port}/auth"
      )
    end
    session[:request_token]
  end

  def set_twitter_client
    Twitter.configure do |config|
      config.consumer_key = ENV['TWITTER_KEY']
      config.consumer_secret = ENV['TWITTER_SECRET']
      config.oauth_token = session[:oauth_token]
      config.oauth_token_secret = session[:oauth_token_secret]
    end
  end

  def authorize_user
    unless logged_in?
      redirect_to login_path and return
    end
  end

  def logged_in?
    session[:oauth_token] && session[:oauth_token_secret]
  end

  helper_method :logged_in?


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to request_token.authorize_url
  end

  def create
    access_token = request_token.get_access_token(:oauth_verifier => params[:oauth_verifier])
    session.delete(:request_token)
    session[:oauth_token] = access_token.params[:oauth_token]
    session[:oauth_token_secret] = access_token.params[:oauth_token_secret]
    redirect_to root_path
  end

  def destroy
    session[:oauth_token] = nil
    session[:oauth_token_secret] = nil
    redirect_to root_path
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_filter :authorize_user

  def index
    set_twitter_client
    @username = Twitter.user.attrs[:name]
    @tweets = Twitter.user_timeline(@username)
  end

  def new
  end

  def create
    set_twitter_client
    begin
      Twitter.update(params[:tweet])
    rescue Exception
      flash[:error] = "Twitter Failed"
      redirect_to tweets_new_path and return
    end
    flash[:success] = "Tweet successfully posted"
    respond_to do |format|
      format.html {redirect_to root_path}
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="errors">
  <%= flash[:errors] %>
</div>

<div class="success">
  <%= flash[:success] %>
</div>

<%= yield %>

</body>
</html>

app/views/tweets/_tweet.html.erb
<li>
  <%= tweet.attrs[:created_at] %>
  <%= tweet.attrs[:text] %>
</li>

app/views/tweets/index.html.erb
<%= link_to "Login to Twitter", login_path unless logged_in? %>
<h1><%= @username %></h1>
<ul>
  <%= render partial: "tweet", collection: @tweets %>
</ul>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>
<%= form_tag(tweets_create_path, method: "post") do %>
  <%= label_tag(:tweet, "Enter your tweet:") %>
  <%= text_field_tag(:tweet) %>
  <%= submit_tag("Post Tweet") %>
<% end %>